### ISSUE TITLE
Example tileset and clarity on what to expect there

### ISSUE THREAD

**Issue by decafboba** [ThibautBremand/2D-MMORPG-client#26]
Fantastic project! Though during the initial phase of setting this up, I encountered some problems having to do with loading tilesets.

For example, tried using some example tilesets: https://github.com/mapeditor/tiled/blob/master/examples/rpg/island.tmx

Mostly getting errors in these places:
```
    // Load the layers from the json files given
    public loadLayers(): void {
        // Retrieve all the layers for the map
        const layers = this.mapToDraw.layers
        // Retrieve tileset
        const tilesets = this.mapToDraw.tilesets
        for (let i = 0; i < tilesets.length; ++i) {
            let image = tilesets[i].image
            image = image.substring(image.search('/tilesets/') + '/tilesets/'.length, image.length)

            this.height = this.mapToDraw.layers[i].height
            this.width = this.mapToDraw.layers[i].width
            
            this.tilesets.push(new Tileset(image, tilesets[i].firstgid))
        }

        for (const layer of layers) {
            if (layer.name === 'Collisions') {
                this.collisions = layer.objects
            } else if (layer.name.substr(0, 3) === 'MAP') {
                this.neighbors.push(layer)
            } else {
                this.layers.push(layer.data)
            }
        }
    }
```
and 
```
drawMap(context) {
    context.setTransform(1, 0, 0, 1, 0, 0); // reset the transform matrix as it is cumulative
    context.clearRect(0, 0, config_namespaceObject.cWIdth, config_namespaceObject.cHeight); // clear the viewport AFTER the matrix is reset
    // Clamp the camera position to the world bounds while centering the camera around the player
    this.translate(-this.camX, -this.camY, context);
    // Draw the layers
    for (const layer of this.layers) {
        let cpt = 0;
        for (let j = 0; j < this.height; ++j) {
            for (let i = 0; i < this.width; ++i) {
                const currentTile = layer[cpt];    // HELP: when i=0 this is just 'e'?
                if (currentTile > 0) {
                    this.electAndDrawTile(currentTile, context, i, j);
                }
                cpt++;
            }
        }
    }
}
```

I think it would be great to have a starting example in this prohject, and more clarity around what kind of files are expected in the `/tilesets/` directory.

**Comment by decafboba** [comment]
Looked like these layers needed to be decompressed. I added the following to do so in `gamemap.ts`:
```
    public loadLayers(): void {
        // ...

        for (const layer of layers) {
            if (layer.name === 'Collisions') {
                this.collisions = layer.objects
            } else if (layer.name.substr(0, 3) === 'MAP') {
                this.neighbors.push(layer)
            } else if (layer.data) {
                this.layers.push(this.uncompress(layer.data))
            }
        }
    }
    
    public uncompress(base64data: string): any {
        // Decode base64 (convert ascii to binary)
        var strData = atob(base64data);
        // Convert binary string to character-number array
        var charData = strData.split('').map(function (x) {
            return x.charCodeAt(0);
        });
        // Turn number array into byte-array
        var binData = new Uint8Array(charData);
        // Pako magic
        var data = pako.inflate(binData);
        // @ts-ignore - Convert gunzipped byteArray back to ascii string:
        var strData = String.fromCharCode.apply(null, new Uint16Array(data));
        return strData;
    }
```

This gets rid of errors and loads the game successfully, although it does not seem to load the map correctly as it's all whitespace.
I see that there is also a `base64.js` file that should probably be responsible for encoding/decoding.

How is this intended to be used? Would love your help @ThibautBremand, thanks!

**Comment by bthibaut** [comment]
Hello @kenvogg, thank you for your message.
I will try to explain, step by step, how to use the tileset you have provided!

1. We need to get the tileset as png, [from this link](https://github.com/mapeditor/tiled/blob/master/examples/rpg/beach_tileset.png).

2. We can create a mew map in Tiled. The first thing to do is to create a new tileset. When you do it, select the png tileset **and check "Embed in map"**. That way, only one generated file will be needed (a json file for a map).
<img width="1091" alt="Screenshot 2021-06-26 at 22 31 42" src="https://user-images.githubusercontent.com/9871294/123525245-86054a00-d6cf-11eb-874c-2cbd19782d95.png">

3. When you map, you need to use [these naming conventions for the layers](https://github.com/ThibautBremand/2D-MMORPG-client/wiki/Create-new-maps), in order to enable collisions and teleportations.

4. Save the map **as json**. The client can only parse json files. Below you will find my json and the original tileset as png:  
[map_example.zip](https://github.com/ThibautBremand/2D-MMORPG-client/files/6720678/map_example.zip)

If you open the .json file for the map, you can see at the bottom that the map references the right tileset image file:
```json
 "tileheight":16,
 "tilesets":[
        {
         "columns":36,
         "firstgid":1,
         "image":"tilesets\/beach_tileset.png",
         "imageheight":416,
         "imagewidth":576,
         "margin":0,
         "name":"beach_tileset",
         "spacing":0,
         "tilecount":936,
         "tileheight":16,
         "tilewidth":16
        }],
 "tilewidth":16,
```

5. You need to insert this .json into your database. To do so, you need to use the [map loader](https://github.com/ThibautBremand/2D-MMORPG-character-creator) and go to your **url:port/gamemap**, for example http://localhost:8080/gamemap
<img width="237" alt="Screenshot 2021-06-26 at 22 47 54" src="https://user-images.githubusercontent.com/9871294/123525389-936f0400-d6d0-11eb-991e-cb014031f7df.png">

6. In the database, we can find the id of the new map
```
select id, name from gamemaps where name='beach_map';
 id |   name    
----+-----------
  5 | beach_map
(1 row)
```

7. We can set the map of one of our characters in the database. ([here's the wiki page to create new characters](https://github.com/ThibautBremand/2D-MMORPG-client/wiki/Create-new-characters))
```
postgres=# select id,gamemap_id,name from characters where id=2;
 id | gamemap_id | name 
----+------------+------
  2 |          1 | test
(1 row)

postgres=# update characters set gamemap_id=5 where id=2;
UPDATE 1
postgres=# select id,gamemap_id,name from characters where id=2;
 id | gamemap_id | name 
----+------------+------
  2 |          5 | test
(1 row)
```

8. Since the tileset you have chosen is size 16x16, you need to change the tileSize config.ts in the client, from 32 to 16
<img width="796" alt="Screenshot 2021-06-26 at 23 06 29" src="https://user-images.githubusercontent.com/9871294/123525748-48a2bb80-d6d3-11eb-8200-1fded7132e6e.png">

9. You need to place the image tileset into your client, and deploy the client. As you saw in my example, I place my tilesets in a tilesets directory (we had `"image":"tilesets\/beach_tileset.png"` in the json map). So, before the deployment, create a "tilesets" directory within your dist directory, and put your image tilesets there
<img width="719" alt="Screenshot 2021-06-26 at 23 15 14" src="https://user-images.githubusercontent.com/9871294/123526095-dd0e1d80-d6d5-11eb-980e-4d4fe1b30e09.png">

 
10. Then run `npm run build` and `npm deploy` from the client, and you can start the server.
<img width="520" alt="Screenshot 2021-06-26 at 23 16 48" src="https://user-images.githubusercontent.com/9871294/123526106-ed25fd00-d6d5-11eb-9dd0-e1baea0deeff.png">

<img width="423" alt="Screenshot 2021-06-26 at 23 27 11" src="https://user-images.githubusercontent.com/9871294/123526130-121a7000-d6d6-11eb-8591-8b391064c086.png">


11. Et voilà!
<img width="597" alt="Screenshot 2021-06-26 at 23 05 49" src="https://user-images.githubusercontent.com/9871294/123525756-5f491280-d6d3-11eb-8799-8d97cee10382.png">


I'm sorry if my explanations are still unclear or tricky, it's been a while since I haven't came back to the project.

I will add a tutorial for this, based on what I have written here, with an example .json map and image tileset. 
The two most complicated things here are:
- Setting up the database, and correctly load characters and map through the [loader](https://github.com/ThibautBremand/2D-MMORPG-character-creator)
- Correctly place the map and tilesets in the client before deploying the client, as I showed at the step 9 and 10.

Feel free to ask any questions, I may also update this message to add details.
Thibaut

**Comment by bthibaut** [comment]
Also, I just saw that collisions are bugged with 16 sized tilesets, since they are considered for 32 sized maps! Something that needs to be fixed when I'll be able to.
